apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  -  name: app
       image: images.my-company.example/app:v4
         resources:
           requests:
             limits:
               cpu: "500m" 

